### ISSUE TITLE
Проблема проверки дистанции на Алкизоне в Зул Амане

### ISSUE THREAD

**Issue by Vitoshka** [Admiliral/DBM-for-Sirus.su#2]
При старте боя появляется данное окно, которое нельзя изменить
![20200323_202918](https://user-images.githubusercontent.com/30943063/77405232-ebc79f80-6dc3-11ea-8120-a12525a54f21.jpg)

**Comment by Admiliral** [comment]
ок, завтра гляну

**Comment by Vitoshka** [comment]
> ок, завтра гляну
Получилось посмотреть?
