### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Vitoshka** [Admiliral/DBM-for-Sirus.su#3]
95x DBM-Core\DBM-Core.lua:1660: attempt to compare nil with number
DBM-Core\DBM-Core.lua:1726: in function `?'
DBM-Core\DBM-Core.lua:351: in function <DBM-Core\DBM-Core.lua:347>

**Comment by Vitoshka** [comment]
**ошибка генерится постоянно и фризит игру**

53x DBM-Core\DBM-Core.lua:1660: attempt to compare nil with number
DBM-Core\DBM-Core.lua:1726: in function `?'
DBM-Core\DBM-Core.lua:351: in function <DBM-Core\DBM-Core.lua:347>

Locals:
self = <table> {
 MoveSpecialWarning = <function> @ DBM-Core\DBM-Core.lua:3400:
 CreatePizzaTimer = <function> @ DBM-Core\DBM-Core.lua:1100:
 MapSizes = <table> {}
 GetModByName = <function> @ DBM-Core\DBM-Core.lua:2747:
 CHAT_MSG_RAID_BOSS_EMOTE = <function> @ DBM-Core\DBM-Core.lua:1950:
 CHAT_MSG_WHISPER = <function> @ DBM-Core\DBM-Core.lua:2511:
 Mods = <table> {}
 ShowUpdateReminder = <function> @ DBM-Core\DBM-Core.lua:1810:
 PLAYER_REGEN_DISABLED = <function> @ DBM-Core\DBM-Core.lua:1870:
 GetDebuff = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:416:
 CreateModLocalization = <function> @ DBM-Core\DBM-Core.lua:4182:
 IsEnabled = <function> @ DBM-Core\DBM-Core.lua:2599:
 HighestRelease = 20200325000000
 AddMsg = <function> @ DBM-Core\DBM-Core.lua:2607:
 SecondsToTime = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:398:
 Schedule = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:444:
 Capitalize = <function> @ DBM-Core\DBM-Core.lua:2661:
 ADDON_LOADED = <function> @ DBM-Core\DBM-Core.lua:535:
 ShowPizzaInfo = <function> @ DBM-Core\DBM-Core.lua:1117:
 BossHealth = <table> {}
 CHAT_MSG_RAID_WARNING = <function> @ DBM-Core\DBM-Core.lua:1529:
 ShowRealDate = <function> @ DBM-Core\DBM-Core.lua:65:
 Revision = 20200325225516
 RegisterEvents = <function> @ DBM-Core\DBM-Core.lua:356:
 COMBAT_LOG_EVENT_UNFILTERED = <function> @ DBM-Core\DBM-Core.lua:385:
 UnSchedule = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:464:
 FilterRaidBossEmote = <function> @ DBM-Core\DBM-Core.lua:381:
 RequestTimers = <function> @ DBM-Core\DBM-Core.lua:2343:
 LFG_PROPOSAL_SUCCEEDED = <function> @ DBM-Core\DBM-Core.lua:1508:
 ForceUpdate = <function> @ DBM-Core\DBM-Core.lua:838:
 Rank = 0
 CHAT_MSG_MONSTER_YELL = <function> @ DBM-Core\DBM-Core.lua:1940:
 GetBuff = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:406:
 LFG_PROPOSAL_SHOW = <function> @ DBM-Core\DBM-Core.lua:1503:
 ReleaseRevision = 20200325000000
 RESURRECT_REQUEST = <function> @ DBM-Core\DBM-Core.lua:1523:
 UnregisterAllEvents = <function> @ DBM-Core\DBM-Core.lua:365:
 GetMod = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:394:
 NewBossMod = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:365:
 AddOns = <table> {}
 UNIT_DESTROYED = <function> @ DBM-Core\DBM-Core.lua:2328:
 Options = <table> {}
 SendTimerInfo = <function> @ DBM-Core\DBM-Core.lua:2420:
 RAID_ROSTER_UPDATE = <function> @ DBM-Core\DBM-Core.lua:1387:
 PLAYER_ENTERING_WORLD = <function> @ DBM-Core\DBM-Core.lua:2449:
 GetModLocalization = <function> @ DBM-Core\DBM-Core.lua:4197:
 UNIT_DIED = <function> @ DBM-Core\DBM-Core.lua:2328:
 GetRaidUnitId = <function> @ DBM-Core\DBM-Core.lua:1414:
 ReceiveCombatInfo = <function> @ DBM-Core\DBM-Core.lua:2356:
 LoadGUI = <function> @ DBM-Core\DBM-Core.lua:1168:
 DefaultOptions = <table> {}
 ShowTestSpecialWarning = <function> @ DBM-Core\DBM-Core.lua:3450:
 UpdateSpecialWarningOptions = <function> @ DBM-Core\DBM-Core.lua:3249:
 GetCurrentInstanceDifficulty = <function> @ DBM-Core\DBM-Core.lua:2311:
 RegisterCallback = 
  ---

**Comment by Vitoshka** [comment]
1x DBM-Core\DBM-Core.lua:1294: table index is nil
DBM-Core\DBM-Core.lua:1392: in function `?'
DBM-Core\DBM-Core.lua:351: in function <DBM-Core\DBM-Core.lua:347>

Locals:
self = <table> {
 MoveSpecialWarning = <function> @ DBM-Core\DBM-Core.lua:3400:
 CreatePizzaTimer = <function> @ DBM-Core\DBM-Core.lua:1100:
 MapSizes = <table> {}
 GetModByName = <function> @ DBM-Core\DBM-Core.lua:2747:
 CHAT_MSG_RAID_BOSS_EMOTE = <function> @ DBM-Core\DBM-Core.lua:1950:
 CHAT_MSG_WHISPER = <function> @ DBM-Core\DBM-Core.lua:2511:
 Mods = <table> {}
 ShowUpdateReminder = <function> @ DBM-Core\DBM-Core.lua:1810:
 PLAYER_REGEN_DISABLED = <function> @ DBM-Core\DBM-Core.lua:1870:
 GetDebuff = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:416:
 CreateModLocalization = <function> @ DBM-Core\DBM-Core.lua:4182:
 IsEnabled = <function> @ DBM-Core\DBM-Core.lua:2599:
 HighestRelease = 20200325000000
 AddMsg = <function> @ DBM-Core\DBM-Core.lua:2607:
 SecondsToTime = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:398:
 Schedule = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:444:
 Capitalize = <function> @ DBM-Core\DBM-Core.lua:2661:
 ADDON_LOADED = <function> @ DBM-Core\DBM-Core.lua:535:
 ShowPizzaInfo = <function> @ DBM-Core\DBM-Core.lua:1117:
 BossHealth = <table> {}
 CHAT_MSG_RAID_WARNING = <function> @ DBM-Core\DBM-Core.lua:1529:
 ShowRealDate = <function> @ DBM-Core\DBM-Core.lua:65:
 Revision = 20200325225516
 RegisterEvents = <function> @ DBM-Core\DBM-Core.lua:356:
 COMBAT_LOG_EVENT_UNFILTERED = <function> @ DBM-Core\DBM-Core.lua:385:
 UnSchedule = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:464:
 FilterRaidBossEmote = <function> @ DBM-Core\DBM-Core.lua:381:
 RequestTimers = <function> @ DBM-Core\DBM-Core.lua:2343:
 LFG_PROPOSAL_SUCCEEDED = <function> @ DBM-Core\DBM-Core.lua:1508:
 ForceUpdate = <function> @ DBM-Core\DBM-Core.lua:838:
 Rank = 0
 CHAT_MSG_MONSTER_YELL = <function> @ DBM-Core\DBM-Core.lua:1940:
 GetBuff = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:406:
 LFG_PROPOSAL_SHOW = <function> @ DBM-Core\DBM-Core.lua:1503:
 ReleaseRevision = 20200325000000
 RESURRECT_REQUEST = <function> @ DBM-Core\DBM-Core.lua:1523:
 UnregisterAllEvents = <function> @ DBM-Core\DBM-Core.lua:365:
 GetMod = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:394:
 NewBossMod = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:365:
 AddOns = <table> {}
 UNIT_DESTROYED = <function> @ DBM-Core\DBM-Core.lua:2328:
 Options = <table> {}
 SendTimerInfo = <function> @ DBM-Core\DBM-Core.lua:2420:
 RAID_ROSTER_UPDATE = <function> @ DBM-Core\DBM-Core.lua:1387:
 PLAYER_ENTERING_WORLD = <function> @ DBM-Core\DBM-Core.lua:2449:
 GetModLocalization = <function> @ DBM-Core\DBM-Core.lua:4197:
 UNIT_DIED = <function> @ DBM-Core\DBM-Core.lua:2328:
 GetRaidUnitId = <function> @ DBM-Core\DBM-Core.lua:1414:
 ReceiveCombatInfo = <function> @ DBM-Core\DBM-Core.lua:2356:
 LoadGUI = <function> @ DBM-Core\DBM-Core.lua:1168:
 DefaultOptions = <table> {}
 ShowTestSpecialWarning = <function> @ DBM-Core\DBM-Core.lua:3450:
 UpdateSpecialWarningOptions = <function> @ DBM-Core\DBM-Core.lua:3249:
 GetCurrentInstanceDifficulty = <function> @ DBM-Core\DBM-Core.lua:2311:
 RegisterCallback = 
  ---

**Comment by Vitoshka** [comment]
1x DBM-Core\DBM-Core.lua:2266: attempt to index global 'DBM_CORE_WHISPER_COMBAT_END_KILL_STATS' (a nil value)
DBM-Core\DBM-Core.lua:2306: in function `OnMobKill'
DBM-Core\DBM-Core.lua:1646: in function `handler'
DBM-Core\DBM-Core.lua:1726: in function `?'
DBM-Core\DBM-Core.lua:351: in function <DBM-Core\DBM-Core.lua:347>

Locals:
self = <table> {
 MoveSpecialWarning = <function> @ DBM-Core\DBM-Core.lua:3400:
 CreatePizzaTimer = <function> @ DBM-Core\DBM-Core.lua:1100:
 MapSizes = <table> {}
 GetModByName = <function> @ DBM-Core\DBM-Core.lua:2747:
 CHAT_MSG_RAID_BOSS_EMOTE = <function> @ DBM-Core\DBM-Core.lua:1950:
 CHAT_MSG_WHISPER = <function> @ DBM-Core\DBM-Core.lua:2511:
 Mods = <table> {}
 ShowUpdateReminder = <function> @ DBM-Core\DBM-Core.lua:1810:
 PLAYER_REGEN_DISABLED = <function> @ DBM-Core\DBM-Core.lua:1870:
 GetDebuff = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:416:
 CreateModLocalization = <function> @ DBM-Core\DBM-Core.lua:4182:
 IsEnabled = <function> @ DBM-Core\DBM-Core.lua:2599:
 HighestRelease = 20200325000000
 AddMsg = <function> @ DBM-Core\DBM-Core.lua:2607:
 SecondsToTime = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:398:
 Schedule = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:444:
 Capitalize = <function> @ DBM-Core\DBM-Core.lua:2661:
 ADDON_LOADED = <function> @ DBM-Core\DBM-Core.lua:535:
 ShowPizzaInfo = <function> @ DBM-Core\DBM-Core.lua:1117:
 BossHealth = <table> {}
 CHAT_MSG_RAID_WARNING = <function> @ DBM-Core\DBM-Core.lua:1529:
 ShowRealDate = <function> @ DBM-Core\DBM-Core.lua:65:
 Revision = 20200325225516
 RegisterEvents = <function> @ DBM-Core\DBM-Core.lua:356:
 COMBAT_LOG_EVENT_UNFILTERED = <function> @ DBM-Core\DBM-Core.lua:385:
 UnSchedule = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:464:
 FilterRaidBossEmote = <function> @ DBM-Core\DBM-Core.lua:381:
 RequestTimers = <function> @ DBM-Core\DBM-Core.lua:2343:
 LFG_PROPOSAL_SUCCEEDED = <function> @ DBM-Core\DBM-Core.lua:1508:
 ForceUpdate = <function> @ DBM-Core\DBM-Core.lua:838:
 Rank = 0
 CHAT_MSG_MONSTER_YELL = <function> @ DBM-Core\DBM-Core.lua:1940:
 GetBuff = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:406:
 LFG_PROPOSAL_SHOW = <function> @ DBM-Core\DBM-Core.lua:1503:
 ReleaseRevision = 20200325000000
 RESURRECT_REQUEST = <function> @ DBM-Core\DBM-Core.lua:1523:
 UnregisterAllEvents = <function> @ DBM-Core\DBM-Core.lua:365:
 GetMod = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:394:
 NewBossMod = <function> @ DBM-BurningCrusade\DBMv3-Compatibility.lua:365:
 AddOns = <table> {}
 UNIT_DESTROYED = <function> @ DBM-Core\DBM-Core.lua:2328:
 Options = <table> {}
 SendTimerInfo = <function> @ DBM-Core\DBM-Core.lua:2420:
 RAID_ROSTER_UPDATE = <function> @ DBM-Core\DBM-Core.lua:1387:
 PLAYER_ENTERING_WORLD = <function> @ DBM-Core\DBM-Core.lua:2449:
 GetModLocalization = <function> @ DBM-Core\DBM-Core.lua:4197:
 UNIT_DIED = <function> @ DBM-Core\DBM-Core.lua:2328:
 GetRaidUnitId = <function> @ DBM-Core\DBM-Core.lua:1414:
 ReceiveCombatInfo = <function> @ DBM-Core\DBM-Core.lua:2356:
 LoadGUI = <function> @ DBM-Core\DBM-Core.lua:1168:
 DefaultOptions = <table> {}
 ShowTestSpecialWarning = <function> @ DBM-Core\DBM-Core.lua:3450:
 UpdateSpecialWarningOptions = <function> @ DBM-Core\DBM-Core.lua:3249:
 GetCurrentInstanceDifficulty = <function> @ DBM-Core\DBM-Core.lua:2311:
 RegisterCallback = 
  ---

**Comment by Vitoshka** [comment]
ещё поймал ошибок

**Comment by Admiliral** [comment]
> ещё поймал ошибок

а тебя стоит аддон меняющий графический интерфейс, шрифт и прочее?
